[package]
name = "cpuid"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"

[dependencies]
vmm-sys-util.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
kvm-bindings.workspace = true
kvm-ioctls.workspace = true
